name: Deploy
on: [push]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          check-latest: true
      - name: Generate deployment ULID
        id: deployment-id
        run: |
          npm i ulid
          echo "::set-output name=ULID::$(npm exec ulid)"
      - name: Get yarn cache directory
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Set asset base URL
        shell: bash
        run: echo "::set-output name=URL::https://cdn.shopify.com/oxygen/%d/%d/${{ steps.deployment-id.outputs.ULID }}/"
        id: base-url
      - name: Install dependencies
        id: 'install-dependencies'
        run: yarn
      - name: Production build
        id: storefront-build
        run: HYDROGEN_ASSET_BASE_URL=${{ steps.base-url.outputs.URL }} yarn build
      - name: Publish to Oxygen
        id: deploy
        uses: shopify/oxygenctl-action@v2
        with:
          deployment_id: ${{ steps.deployment-id.outputs.ULID }}
          oxygen_deployment_token: ${{ secrets.OXYGEN_DEPLOYMENT_TOKEN }}
      # Create GitHub Deployment
      - name: Create GitHub Deployment
        uses: shopify/github-deployment-action@v1
        if: always()
        with:
          token: ${{ github.token }}
          environment: 'preview'
          preview_url: ${{ steps.deploy.outputs.url }}
          description: ${{ github.event.head_commit.message }}